// Site search index, a plain array so it is easy to extend as pages are added.
// Each entry: title, url, category (shown as a small label), icon (Font Awesome class), keywords (extra terms to match on).
const SEARCH_INDEX = [
  { title: "Home", url: "index.html", category: "Page", icon: "fa-house" },
  { title: "About Us", url: "about.html", category: "Page", icon: "fa-circle-info" },
  { title: "Contact", url: "contact.html", category: "Page", icon: "fa-envelope" },
  { title: "Book a Consultation", url: "consultation.html", category: "Page", icon: "fa-calendar-check", keywords: "schedule book appointment apply" },
  { title: "Make a Payment", url: "make-payment.html", category: "Page", icon: "fa-credit-card", keywords: "invoice billing pay" },
  { title: "FAQ", url: "faq.html", category: "Page", icon: "fa-circle-question" },
  { title: "Testimonials", url: "testimonials.html", category: "Page", icon: "fa-star", keywords: "reviews clients" },
  { title: "Careers", url: "careers.html", category: "Page", icon: "fa-briefcase", keywords: "jobs hiring" },
  { title: "Global Offices", url: "locations.html", category: "Page", icon: "fa-earth-americas", keywords: "locations offices map" },
  { title: "Notable Matters", url: "matters.html", category: "Page", icon: "fa-trophy", keywords: "deals cases track record" },
  { title: "Recognition", url: "recognition.html", category: "Page", icon: "fa-award", keywords: "rankings awards chambers" },
  { title: "Insights Hub", url: "blog.html", category: "Page", icon: "fa-newspaper", keywords: "blog articles alerts videos" },
  { title: "Publications", url: "publications.html", category: "Page", icon: "fa-file-lines", keywords: "alerts guides reports" },
  { title: "Events", url: "events.html", category: "Page", icon: "fa-calendar", keywords: "webinar panel cle" },
  { title: "Diversity & Inclusion", url: "diversity.html", category: "Page", icon: "fa-people-group", keywords: "dei culture" },
  { title: "Pro Bono", url: "pro-bono.html", category: "Page", icon: "fa-hand-holding-heart", keywords: "community impact" },
  { title: "Sustainability & ESG", url: "sustainability.html", category: "Page", icon: "fa-leaf", keywords: "environment climate" },
  { title: "Alumni Network", url: "alumni.html", category: "Page", icon: "fa-user-group" },
  { title: "Firm at a Glance", url: "glance.html", category: "Page", icon: "fa-chart-simple", keywords: "stats numbers data" },
  { title: "Privacy Policy", url: "privacy-policy.html", category: "Page", icon: "fa-shield-halved" },
  { title: "Terms of Service", url: "terms.html", category: "Page", icon: "fa-gavel" },

  { title: "Practice Areas", url: "practice-areas.html", category: "Overview", icon: "fa-briefcase" },
  { title: "Corporate & M&A", url: "practice-areas.html#corporate", category: "Practice Area", icon: "fa-building", keywords: "mergers acquisitions" },
  { title: "Capital Markets", url: "practice-areas.html#capital-markets", category: "Practice Area", icon: "fa-chart-line", keywords: "ipo debt offerings" },
  { title: "Private Equity", url: "practice-areas.html#private-equity", category: "Practice Area", icon: "fa-sack-dollar", keywords: "buyouts funds" },
  { title: "Antitrust & Competition", url: "practice-areas.html#antitrust", category: "Practice Area", icon: "fa-scale-unbalanced", keywords: "merger clearance cartel" },
  { title: "Litigation & Arbitration", url: "practice-areas.html#litigation", category: "Practice Area", icon: "fa-gavel", keywords: "disputes trial" },
  { title: "Restructuring", url: "practice-areas.html#restructuring", category: "Practice Area", icon: "fa-arrows-rotate", keywords: "bankruptcy chapter 11" },
  { title: "Intellectual Property", url: "practice-areas.html#ip", category: "Practice Area", icon: "fa-lightbulb", keywords: "patents trademarks ip" },
  { title: "Tax", url: "practice-areas.html#tax", category: "Practice Area", icon: "fa-file-invoice-dollar" },
  { title: "Employment", url: "practice-areas.html#employment", category: "Practice Area", icon: "fa-people-group", keywords: "labor hr" },
  { title: "Real Estate", url: "practice-areas.html#real-estate", category: "Practice Area", icon: "fa-city" },
  { title: "Family Law", url: "practice-areas.html#family", category: "Practice Area", icon: "fa-people-roof", keywords: "divorce custody" },
  { title: "Estate Planning", url: "practice-areas.html#estate", category: "Practice Area", icon: "fa-file-signature", keywords: "wills trusts" },
  { title: "Government Benefits & Disability", url: "practice-areas.html#benefits", category: "Practice Area", icon: "fa-hand-holding-heart", keywords: "social security ssdi ssi va veterans disability medicaid snap unemployment" },
  { title: "Probate & Estate Administration", url: "practice-areas.html#probate", category: "Practice Area", icon: "fa-scroll", keywords: "will contest executor administrator intestate" },
  { title: "Personal Injury", url: "practice-areas.html#personal-injury", category: "Practice Area", icon: "fa-user-injured", keywords: "accident negligence car crash injury claim" },
  { title: "Wrongful Death", url: "practice-areas.html#wrongful-death", category: "Practice Area", icon: "fa-dove", keywords: "fatal accident survival action next of kin" },
  { title: "Criminal Defense & White Collar", url: "practice-areas.html#criminal", category: "Practice Area", icon: "fa-gavel" },

  { title: "Industries", url: "industries.html", category: "Overview", icon: "fa-industry" },
  { title: "Financial Services", url: "industries.html#financial-services", category: "Industry", icon: "fa-building-columns" },
  { title: "Technology", url: "industries.html#technology", category: "Industry", icon: "fa-microchip" },
  { title: "Energy & Infrastructure", url: "industries.html#energy", category: "Industry", icon: "fa-bolt" },
  { title: "Healthcare & Life Sciences", url: "industries.html#healthcare", category: "Industry", icon: "fa-heart-pulse" },
  { title: "Private Capital", url: "industries.html#private-capital", category: "Industry", icon: "fa-coins" },
  { title: "Real Estate", url: "industries.html#real-estate", category: "Industry", icon: "fa-city" },
  { title: "Industrials & Manufacturing", url: "industries.html#industrials", category: "Industry", icon: "fa-industry" },
  { title: "Media & Telecom", url: "industries.html#media", category: "Industry", icon: "fa-satellite-dish" },
  { title: "Consumer & Retail", url: "industries.html#consumer", category: "Industry", icon: "fa-bag-shopping" },
  { title: "Transportation", url: "industries.html#transport", category: "Industry", icon: "fa-plane" },

  { title: "Attorneys", url: "attorneys.html", category: "Overview", icon: "fa-user-tie" },
  { title: "John Doe, Esq.", url: "attorney-john-doe.html", category: "Attorney", icon: "fa-user-tie", keywords: "corporate m&a senior partner" },
  { title: "Jane Smith, Esq.", url: "attorney-jane-smith.html", category: "Attorney", icon: "fa-user-tie", keywords: "family law partner" },
  { title: "Michael Brown, Esq.", url: "attorney-michael-brown.html", category: "Attorney", icon: "fa-user-tie", keywords: "criminal defense white collar" },
  { title: "Emily Johnson, Esq.", url: "attorney-emily-johnson.html", category: "Attorney", icon: "fa-user-tie", keywords: "estate planning" },
  { title: "David Okafor, Esq.", url: "attorney-david-okafor.html", category: "Attorney", icon: "fa-user-tie", keywords: "corporate associate" },
  { title: "Sarah Nwosu, Esq.", url: "attorney-sarah-nwosu.html", category: "Attorney", icon: "fa-user-tie", keywords: "family law associate" },
  { title: "Robert Kim, Esq.", url: "attorney-robert-kim.html", category: "Attorney", icon: "fa-user-tie", keywords: "criminal defense associate" },
  { title: "Grace Adeyemi, Esq.", url: "attorney-grace-adeyemi.html", category: "Attorney", icon: "fa-user-tie", keywords: "estate planning associate" },
  { title: "Nia Brooks, Esq.", url: "attorney-nia-brooks.html", category: "Attorney", icon: "fa-user-tie", keywords: "government benefits disability ssdi ssi va veterans chair" },
  { title: "Jordan Hale, Esq.", url: "attorney-jordan-hale.html", category: "Attorney", icon: "fa-user-tie", keywords: "personal injury wrongful death chair" },

  { title: "Chicago Office (HQ)", url: "locations.html#office-chicago", category: "Office", icon: "fa-location-dot" },
  { title: "New York Office", url: "locations.html#office-newyork", category: "Office", icon: "fa-location-dot" },
  { title: "Washington DC Office", url: "locations.html#office-dc", category: "Office", icon: "fa-location-dot" },
  { title: "Los Angeles Office", url: "locations.html#office-la", category: "Office", icon: "fa-location-dot" },
  { title: "London Office", url: "locations.html#office-london", category: "Office", icon: "fa-location-dot" },
  { title: "Paris Office", url: "locations.html#office-paris", category: "Office", icon: "fa-location-dot" },
  { title: "Frankfurt Office", url: "locations.html#office-frankfurt", category: "Office", icon: "fa-location-dot" },
  { title: "Dubai Office", url: "locations.html#office-dubai", category: "Office", icon: "fa-location-dot" },
  { title: "Johannesburg Office", url: "locations.html#office-johannesburg", category: "Office", icon: "fa-location-dot" },
  { title: "Singapore Office", url: "locations.html#office-singapore", category: "Office", icon: "fa-location-dot" },
  { title: "Hong Kong Office", url: "locations.html#office-hongkong", category: "Office", icon: "fa-location-dot" },
  { title: "Tokyo Office", url: "locations.html#office-tokyo", category: "Office", icon: "fa-location-dot" },
  { title: "Sydney Office", url: "locations.html#office-sydney", category: "Office", icon: "fa-location-dot" },
  { title: "S\u00e3o Paulo Office", url: "locations.html#office-saopaulo", category: "Office", icon: "fa-location-dot" },
];
